#!/usr/bin/env python
"""
Generate RSA key pair for JWT signing.

Usage:
    python scripts/generate_keys.py

This script generates:
- RSA 2048-bit private key
- Corresponding public key
- Base64 encoded versions for environment variables
"""

import base64
import os
from pathlib import Path

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa


def generate_rsa_keys():
    """Generate RSA key pair for JWT signing."""
    print("Generating RSA-2048 key pair...")

    # Generate private key
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend(),
    )

    # Get public key
    public_key = private_key.public_key()

    # Serialize private key to PEM format
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    # Serialize public key to PEM format
    public_pem = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    # Create keys directory
    keys_dir = Path(__file__).parent.parent / "keys"
    keys_dir.mkdir(exist_ok=True)

    # Save keys to files
    private_key_path = keys_dir / "private.pem"
    public_key_path = keys_dir / "public.pem"

    with open(private_key_path, "wb") as f:
        f.write(private_pem)
    os.chmod(private_key_path, 0o600)

    with open(public_key_path, "wb") as f:
        f.write(public_pem)

    # Generate base64 encoded versions for environment variables
    private_b64 = base64.b64encode(private_pem).decode("utf-8")
    public_b64 = base64.b64encode(public_pem).decode("utf-8")

    print("\n" + "=" * 60)
    print("RSA Key Pair Generated Successfully!")
    print("=" * 60)
    print(f"\nKey files saved to: {keys_dir}")
    print(f"  - Private key: {private_key_path}")
    print(f"  - Public key: {public_key_path}")

    print("\n" + "-" * 60)
    print("Base64 encoded keys for environment variables:")
    print("-" * 60)

    print("\nJWT_PRIVATE_KEY (add to .env):")
    print(private_b64[:80] + "...")

    print("\nJWT_PUBLIC_KEY (add to .env):")
    print(public_b64[:80] + "...")

    # Save base64 keys to a file for easy copying
    env_example_path = keys_dir / "jwt_keys.env"
    with open(env_example_path, "w") as f:
        f.write(f"# JWT Keys (Base64 encoded)\n")
        f.write(f"# Generated by generate_keys.py\n\n")
        f.write(f"JWT_PRIVATE_KEY={private_b64}\n\n")
        f.write(f"JWT_PUBLIC_KEY={public_b64}\n")

    print(f"\nBase64 keys saved to: {env_example_path}")
    print("\nIMPORTANT: Keep your private key secure and never commit it to version control!")


def generate_secret_key():
    """Generate a random secret key."""
    import secrets
    return secrets.token_urlsafe(32)


if __name__ == "__main__":
    generate_rsa_keys()

    print("\n" + "-" * 60)
    print("Additional secret key for general use:")
    print("-" * 60)
    print(f"\nSECRET_KEY={generate_secret_key()}")
